### ISSUE TITLE
Broken on older version

### ISSUE THREAD

**Issue by eggnaut** [Lundeful/ContributionCorner#2]
Doesn't work for macOS Monterey 12.6.3

When I double click to open/run the app, I get an error saying the app doesn't work on my version of macOS. From the screenshots, this is so amazing, would love to see it updated! 😄 

EDIT: the error message says the app was made for macOS 13 or later

**Comment by Lundeful** [comment]
Hi 😊

Thanks a lot for reporting the issue, sorry that it doesn't work. I will investigate and try to fix it 😄 . I'll let you know once it's safe to try again.

**Comment by eggnaut** [comment]
Thank you so much!

**Comment by eggnaut** [comment]
![Screen Shot 2023-02-19 at 5 04 46 PM](https://user-images.githubusercontent.com/120997069/219987353-f67bc789-f083-4c01-aa0a-b74227b5edf6.png)

**Comment by Lundeful** [comment]
Thanks for the screenshot! 😄 

I see that by setting the deployment target to anything lower than 13.0 there will have to be some changes made, as MenuBarExtra and the package FluidMenuBarExtra doesn't work. I have already thought about moving away from MenuBarExtra and that package and start using NSPopover instead, as it is more fitting for the app anyway. So this is something I'll hop onto first thing.

Then I will be able to support MacOS version 12.0 and upwards. By moving to 11.0 (Big Sur) I would lose too many nice-to-haves with SwiftUI so 12.0 will be the final minimum target.

I'll try to get a fix out tomorrow, it's late here now. 

Thanks for the input!

PS: Might I ask how you found this repo? :) Just searched on GitHub?

**Comment by eggnaut** [comment]
Oh thank you! I completely forgot that _I_ had the deprecated version of macOS, not the app ;-; Looks like I forgot 12 < 13...

As for how I found this repository, I was randomly searching Github for repos related to Github Contribution Graphs. Went through 2 pages of results.

**Comment by eggnaut** [comment]
🎉 Yay thanks!

**Comment by Lundeful** [comment]
@eggnaut I've merged in a fix, and uploaded the new release. Please let me know if it works now 😄

**Comment by eggnaut** [comment]
Downloaded, tested, works beautifully:
![Screen Shot 2023-02-19 at 6 09 02 PM](https://user-images.githubusercontent.com/120997069/219993061-e25c44f7-a600-45d1-a183-d41311459dac.png)
![Screen Shot 2023-02-19 at 6 09 27 PM](https://user-images.githubusercontent.com/120997069/219993105-f401d49b-d90a-4c95-816b-0094ecfc9b7d.png)

**Comment by Lundeful** [comment]
Fantastic! 😄 Thanks for the help. If not for your issue I probably wouldn't have thought to add 12.0 support.

Yeah I think I forgot to validate it. I'm still new to all the signing stuff. I'll try to upload a proper signed one.

**Comment by eggnaut** [comment]
> Fantastic! 😄 Thanks for the help. If not for your issue I probably wouldn't have thought to add 12.0 support.
> 
> Yeah I think I forgot to validate it. I'm still new to all the signing stuff. I'll try to upload a proper signed one.

Thank you!

No worries 😀

**Comment by Lundeful** [comment]
@eggnaut Hi, I've re-uploaded a notarised version of the app. So now it should open properly without any workarounds. And hopefully it feel a lot safer to use since it's been analysed by Apple during the notarisation process  :)

Link to the v1.1 latest release
https://github.com/Lundeful/ContributionCorner/releases/tag/1.1

**Comment by eggnaut** [comment]
@Lundeful - Yep, Apple _loves_ to freak out over unsigned apps lol. I'll test it out when I get on my Mac.
